---

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install epel-release
  yum:
    name: epel-release
    state: latest


- name: Install pip3
  yum:
    name: python3-pip
    state: present

- name: Install git
  yum:
    name: git
    state: present

- name: Install python-docker-py
  yum:
    name: python-docker-py
    state: present


- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Install python-setuptools
  yum:
    name: python-setuptools
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: yes

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: present
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

#
- name: pip installs
  include: pip.yml

- name: Users
  include: users.yml