---
- name: Remove default docker packages
  ansible.builtin.package:
    name:  "{{item}}"
    state: absent
  with_items: "{{unwanted_docker_packages}}"
  tags:
    - package_cleanup
    - docker_packages
    - docker

- name: Install yum-utils
  ansible.builtin.package:
    name: yum-utils
    state: present
  tags:
    - docker_packages
    - docker


#- name: Docker Repo
#  get_url:
#    url: https://download.docker.com/linux/centos/docker-ce.repo
#    dest: /etc/yum.repos.d/docker-ce.repo

- name: Add Docker CE repository
  become: true
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  tags:
    - docker_packages
    - docker

- name: Install docker packages
  ansible.builtin.package:
    name: "{{item}}"
    state: present
  with_items: "{{docker_packages}}"
  tags:
    - docker_packages
    - docker


- name: Ensure docker is running 
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker_service
    - docker

- name: make sure ansible can run docker
  ansible.builtin.user:
    name: "{{item}}"
    groups: docker
    append: yes
  with_items: "{{docker_users}}"
  tags:
    - docker_service
    - docker

- name: Install docker-compose-plugin as defined in defaults
  ansible.builtin.package:
    name: docker-compose-plugin-{{docker_compose_version}}.x86_64
    state: present
  tags:
    - docker_compose
    - docker

- name: Add alias to bashrc file
  lineinfile:
    path: /etc/bashrc
    line: "alias docker-compose='docker compose '"
    state: present
    insertafter: EOF
  tags:
    - docker_compose_alias
    - docker_compose
    - docker

