---
- debug:
    msg: "OS Version - {{ ansible_distribution}}"

- name: Install docker
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars






