---
- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ docker_user }}"
    groups: [docker]
    append: true
  loop_control:
    loop_var: docker_user
  with_items: "{{ docker_users }}"
  when: docker_users | length > 0
  tags:
    - docker_users
    
- name: Install python docker so ansible can use it
  pip:
    name: docker
    executable: /usr/bin/pip3

